CREATE TABLE IF NOT EXISTS Usuario (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(120) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Senha VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255),
    DataRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Telefone VARCHAR(30),
    DataNascimento DATE,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_usuario_email (Email)
);